---
- name: Play para la instalacion y configuracion inicial de webserver
  hosts: webserver
  become: yes

  tasks:
  - name: Httpd installed
    ansible.builtin.dnf:
      name: "{{ package }}"
      state: present
  - name: Httpd enabled
    ansible.builtin.systemd_service:
      name: "{{ service }}"
      enabled: true
      state: started
  - name: Firewalld enable
    ansible.posix.firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: true
      immediate: true
    loop: "{{ firewall_service }}" 
  - name: Archivo index custom
    ansible.builtin.template:
      src: ../templates/index.j2
      dest: /var/www/html/index.html
      owner: apache
      group: apache
      mode: u=rw,g=r,o=r

