---
- name: Play para la instalacion y configuracion inicial de webserver
  hosts: webserver
  become: yes

  tasks:
  - name: Httpd installed
    ansible.builtin.dnf:
      name: httpd
      state: present
  - name: Httpd enabled
    ansible.builtin.systemd_service:
      name: httpd
      enabled: true
      state: started
  - name: Firewalld enable
    ansible.posix.firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: true
      immediate: true
      loop: 
        - http
        - https
